### ISSUE TITLE
"<Plug>_" is inserted as text when inserting multiple characters

### ISSUE THREAD

**Issue by andyearnshaw** [terryma/vim-multiple-cursors#235]
I'm having this issue since I updated a few weeks ago.  I highlight multiple words, then switch to insert mode (with <kbd>c</kbd>, <kbd>A</kbd>, etc).  The first character I enter is fine, but every character after that has `<Plug>_` appended to it.

This is demonstrated in the following short asciinema video:

[![asciicast](https://asciinema.org/a/DNSQ3YbbLE0pjKc8np0s4lItj.png)](https://asciinema.org/a/DNSQ3YbbLE0pjKc8np0s4lItj)

What can I do to debug and help fix this problem?

**Comment by voltux** [comment]
I've got the same one here. <Plug>_ gets inserted seemingly randomly or if I stop typing a second later or so. In insert mode that is.

**Comment by MiguelMoll** [comment]
Same here using neovim. FWIW, I've been experiencing this issue _I think_ since early last fall.

**Comment by perrupa** [comment]
I'm experiencing this as well.

![iterm](https://user-images.githubusercontent.com/1577452/34844513-c18d4858-f6df-11e7-98cc-cec6faf318df.gif)


`neovim -v`
<details>

```

→  nvim -v                                                                                                                                        [df5a1c439]
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/config -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/include
Compiled by brew@HighSierra-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2/share/nvim"

Run :checkhealth for more info
```

</details>

and I'm using deoplete for autocompletion. If there are any other details I can provide, I'm more than willing 👍

**Comment by lwm** [comment]
Oh darn, same here. At least it is reported :)

**Comment by kiooss** [comment]
Same issue with deoplete for autocompletion.

**Comment by richox** [comment]
conflicts with deoplete, after calling deoplete#disable() everything works ok.

**Comment by antoinemadec** [comment]
@perrupa @richox @andyearnshaw , could you please try to:

- update vim-multiple-cursors
- don't define Multiple_cursors_*() functions

 and see if the bug has disappeared or not ?

We have changed a lot of things regarding the insert mode recently, things that should have fixed that issue.
Thanks in advance!

**Comment by andyearnshaw** [comment]
@antoinemadec I can confirm the latest update fixes the problem for me.  Thanks :)

**Comment by voltux** [comment]
@antoinemadec fwiw issue fixed here too, ty!

**Comment by antoinemadec** [comment]
Noice! Closing the ticket since issue has been resolved.

**Comment by antoinemadec** [comment]
This issue still exists, it won't be fixed (unless someone wants to do a pull request).
In the meantime here is the updated fix - keeping the state of deoplete before multicursor.
Please use the following in your vimrc:

```vim
func! Multiple_cursors_before()
  if deoplete#is_enabled()
    call deoplete#disable()
    let g:deoplete_is_enable_before_multi_cursors = 1
  else
    let g:deoplete_is_enable_before_multi_cursors = 0
  endif
endfunc
func! Multiple_cursors_after()
  if g:deoplete_is_enable_before_multi_cursors
    call deoplete#enable()
  endif
endfunc
```

**Comment by kalbasit** [comment]
@antoinemadec you should probably re-open this issue.

**Comment by Leandros** [comment]
Still exists. I'm getting it regularly, too.

**Comment by antoinemadec** [comment]
Reopen issue.
The issue occurs with the insert mappings using ```<Plug>```.

@Leandros , there already is something in the README regarding the ```Multiple_cursors_*``` functions.
Please feel free to create a PR if you want to refactor the README.

Thanks,
Antoine
